- Enhancing CloudFlare IP whitelisting routine. - Adding update routines for CloudFlare IP whitelisting. - Reorganized and refactored bootstrap updater for production servers.

diff --git a/src/setups/cleanup b/src/setups/cleanup
--- a/src/setups/cleanup
+++ b/src/setups/cleanup
@@ -1,44 +1,41 @@
 #!/usr/bin/env bash
 
-if [[ "${CFG_IS_INSTALLER}" == 1 || "${CFG_IS_UPDATER}" == 1 ]]; then
+# Cleanup archives.
 
-  # Cleanup archives.
+if ! is-vm || is-4pkg; then
+  apt-get autoremove --yes;
+  apt-get clean --yes;
+  if is-4pkg; then # Remove package lists.
+    rm --force --recursive /var/lib/apt/lists/*;
+  fi; # Running `apt-get update` will restore these.
+fi;
+# Remove root SSH key (security).
+# Note that VMs don't generally require an SSH key.
+# If an administrator uploads them though, leave them there.
 
-  if ! is-vm || is-4pkg; then
-    apt-get autoremove --yes; apt-get clean --yes;
-    if is-4pkg; then # Remove package lists.
-      rm --force --recursive /var/lib/apt/lists/*;
-    fi; # Running `apt-get update` will restore these.
-  fi;
-  # Remove root SSH key (security).
-  # Note that VMs don't generally require an SSH key.
-  # If an administrator uploads them though, leave them there.
+if ! is-vm || is-4pkg; then
+  rm --force /root/.ssh/id_rsa;
+  rm --force /root/.ssh/ws-bot-np;
+  rm --force /home/"${CFG_ADMIN_USERNAME}"/.ssh/id_rsa;
+  rm --force /home/"${CFG_ADMIN_USERNAME}"/.ssh/ws-bot-np;
+fi;
+# Cleanup temporary files.
 
-  if ! is-vm || is-4pkg; then
-    rm --force /root/.ssh/id_rsa;
-    rm --force /root/.ssh/ws-bot-np;
-    rm --force /home/"${CFG_ADMIN_USERNAME}"/.ssh/id_rsa;
-    rm --force /home/"${CFG_ADMIN_USERNAME}"/.ssh/ws-bot-np;
-  fi;
-  # Cleanup temporary files.
+if is-4pkg; then
+  rm --force --recursive /tmp/*;
+fi;
+# Zero-out drive when packaging. See: <http://jas.xyz/1MGoPML>
+# Resolves fragmentation issues and reduces the size of the disk.
 
-  if is-4pkg; then
-    rm --force --recursive /tmp/*;
-  fi;
-  # Zero-out drive when packaging. See: <http://jas.xyz/1MGoPML>
-  # Resolves fragmentation issues and reduces the size of the disk.
+if is-4pkg; then
+  dd if=/dev/zero of=/EMPTY bs=1M &>/dev/null || true;
+  rm -f /EMPTY; # ↑ See: <http://jas.xyz/1MGxHCj>
+fi;
+# Erase shell history when packaging.
+# See: <http://jas.xyz/1MGpmOK>
 
-  if is-4pkg; then
-    dd if=/dev/zero of=/EMPTY bs=1M &>/dev/null || true;
-    rm -f /EMPTY; # ↑ See: <http://jas.xyz/1MGxHCj>
-  fi;
-  # Erase shell history when packaging.
-  # See: <http://jas.xyz/1MGpmOK>
-
-  if is-4pkg; then
-    rm --force /root/.bash_history;
-    rm --force /home/vagrant/.bash_history;
-    history -c; # Erase current history.
-  fi;
-
+if is-4pkg; then
+  rm --force /root/.bash_history;
+  rm --force /home/vagrant/.bash_history;
+  history -c; # Erase current history.
 fi;
