Updating Bash utils.

diff --git a/src/bin/sharefile b/src/bin/sharefile
--- a/src/bin/sharefile
+++ b/src/bin/sharefile
@@ -5,13 +5,52 @@
 . /bootstrap/src/bash/strict-mode;
 . /bootstrap/src/bash/functions;
 
-# Validate incoming args.
+# Intialize.
 
-file="${1:-}";
-recipient="${2:-}";
+file='';
+dir='';
+basename='';
+basename_no_ext='';
+recipient='';
 
-if [[ ! -f "${file}" ]]; then
-  echo 'Expecting input file.'; exit 1;
+# Parse options.
+
+short_options='f:r:';
+long_options='file:,recipient:';
+options="$(getopt --options "${short_options}" --longoptions "${long_options}" -- "${@}")";
+
+eval set -- "${options}"; while true; do
+	 case "${1}" in
+			-f|--file)
+				file="${2}";
+				shift 2;
+				;;
+			-r|--recipient)
+				recipient="${2}";
+				shift 2;
+				;;
+			--) shift 1; break;
+				;;
+			*) echo 'Internal error.'; exit 1;
+				;;
+	 esac;
+done;
+
+if [[ -z "${file}" && -n "${1:-}" ]]; then
+	file="${1}"; fi;
+
+dir="${file%/*}";
+basename="${file##*/}";
+basename_no_ext="${basename%.*}";
+
+if [[ -z "${recipient}" && -n "${2:-}" ]]; then
+	recipient="${2}"; fi;
+
+# Validate options.
+
+if [[ -z "${file}" || ! -f "${file}" || -z "${dir}" || -z "${basename}" || -z "${basename_no_ext}" ]]; then
+	echo 'Expecting a parseable input file.';
+	exit 1; # Error status.
 fi;
 
 # Upload for sharing via transfer.sh.
@@ -21,7 +60,7 @@ if [[ -n "${recipient}" ]]; then
   echo 'Uploading encrypted file for: '"${recipient}";
 
   link="$(cat "${file}" \
-    | keybase encrypt "${recipient}" \
+    | keybase pgp encrypt "${recipient}" \
     | curl --upload-file '-' https://transfer.sh/"$(basename "${file}")" \
     )";
 
