- Adding optional `CFG_AWS_ACCESS_KEY_ID` configuration variable. - Adding optional `CFG_AWS_SECRET_ACCESS_KEY` configuration variable. - Adding new utility `sharefile-s3`, which depends on the new configuration variables. - Enhancing existing `sharefile` utility. General code cleanup and mild optimization. - Moving `export-data` and `import-data` into default `$PATH` for easier access.

diff --git a/src/bin/sharefile b/src/bin/sharefile
--- a/src/bin/sharefile
+++ b/src/bin/sharefile
@@ -20,38 +20,42 @@ long_options='file:,recipient:';
 options="$(getopt --options "${short_options}" --longoptions "${long_options}" -- "${@}")";
 
 eval set -- "${options}"; while true; do
-	 case "${1}" in
-			-f|--file)
-				file="${2}";
-				shift 2;
-				;;
-			-r|--recipient)
-				recipient="${2}";
-				shift 2;
-				;;
-			--) shift 1; break;
-				;;
-			*) echo 'Internal error.'; exit 1;
-				;;
-	 esac;
+  case "${1}" in
+    -f|--file)
+      file="${2}";
+      shift 2;
+      ;;
+    -r|--recipient)
+      recipient="${2}";
+      shift 2;
+      ;;
+    --) shift 1; break;
+      ;;
+    *) echo 'Internal error.'; exit 1;
+      ;;
+  esac;
 done;
 
 if [[ -z "${file}" && -n "${1:-}" ]]; then
-	file="${1}"; fi;
+  file="${1}"; fi;
+
+if [[ -z "${recipient}" && -n "${2:-}" ]]; then
+  recipient="${2}"; fi;
 
 dir="${file%/*}";
 basename="${file##*/}";
 basename_no_ext="${basename%.*}";
 
-if [[ -z "${recipient}" && -n "${2:-}" ]]; then
-	recipient="${2}"; fi;
-
 # Validate options.
 
 if [[ -z "${file}" || ! -f "${file}" || -z "${dir}" || -z "${basename}" || -z "${basename_no_ext}" ]]; then
-	echo 'Expecting a parseable input file.';
-	exit 1; # Error status.
+  echo 'Expecting a parseable input file.';
+  exit 1; # Error status.
 fi;
+
+# Make sure directory exists.
+
+mkdir --parents /tmp/sharefile;
 
 # Upload for sharing via transfer.sh.
 
@@ -59,15 +63,16 @@ if [[ "${recipient}" == symmetric ]]; then
 
   echo 'Uploading encrypted file w/ symmetric key.';
 
-	gpg2 --armor --symmetric --cipher-algo AES256 \
-		--output /tmp/sharefile-"${basename}".gpg "${file}";
+  gpg_file=/tmp/sharefile/"$(uuidgen)"-"${basename}".gpg;
+	gpg_basename="${gpg_file##*/}"; # Use hashed file name.
 
-  link="$(cat /tmp/sharefile-"${basename}".gpg \
-    | curl --request PUT --upload-file '-' https://transfer.sh/"${basename}".gpg \
-    )";
-	rm /tmp/sharefile-"${basename}".gpg; # Cleanup `.gpg` file.
+  gpg2 --armor --symmetric --cipher-algo AES256 --output "${gpg_file}" "${file}";
+  link="$(curl --request PUT --upload-file "${gpg_file}" https://transfer.sh/"${gpg_basename}")";
 
-  echo "${link}"; echo 'Link expires in 14 days.';
+  rm "${gpg_file}"; # Cleanup `.gpg` file.
+
+  echo -n "${link}" | pbcopy; echo "${link}";
+  echo 'Copied to clipboard; expires in 14 days.';
 
 # Upload for sharing via transfer.sh.
 
@@ -75,18 +80,24 @@ elif [[ -n "${recipient}" ]]; then
 
   echo 'Uploading encrypted file for: '"${recipient}";
 
-  link="$(cat "${file}" \
-    | keybase pgp encrypt "${recipient}" \
-    | curl --request PUT --upload-file '-' https://transfer.sh/"${basename}".gpg \
-    )";
-  echo "${link}"; echo 'Link expires in 14 days.';
+  gpg_file=/tmp/sharefile/"$(uuidgen)"-"${basename}".gpg;
+	gpg_basename="${gpg_file##*/}"; # Use hashed file name.
 
-else # Unencrypted file (default behavior w/ no recipient).
+	keybase pgp encrypt --infile "${file}" --outfile "${gpg_file}" "${recipient}";
+  link="$(curl --request PUT --upload-file "${gpg_file}" https://transfer.sh/"${gpg_basename}")";
+
+  rm "${gpg_file}"; # Cleanup `.gpg` file.
+
+  echo -n "${link}" | pbcopy; echo "${link}";
+  echo 'Copied to clipboard; expires in 14 days.';
+
+else # Unencrypted (default behavior w/ no recipient).
 
   echo 'Uploading file for public sharing.';
 
-  link="$(cat "${file}" \
-    | curl --request PUT --upload-file '-' https://transfer.sh/"${basename}" \
-    )";
-  echo "${link}"; echo 'Link expires in 14 days.';
+	une_basename="$(uuidgen)"-"${basename}"; # Use hashed file name.
+  link="$(curl --request PUT --upload-file "${file}" https://transfer.sh/"${une_basename}")";
+
+  echo -n "${link}" | pbcopy; echo "${link}";
+  echo 'Copied to clipboard; expires in 14 days.';
 fi;
