Bash/Git utility functions + a little refactoring.

diff --git a/src/bash/funcs/create-user b/src/bash/funcs/create-user
--- a/src/bash/funcs/create-user
+++ b/src/bash/funcs/create-user
@@ -25,9 +25,9 @@ function create-user() {
           pass="${2}";
           shift 2;
           ;;
-        --) shift; break;
+        --) shift 1; break;
           ;;
-        *) echo 'Invalid option: '"${1}"; exit 1;
+        *) echo 'Internal error.'; exit 1;
           ;;
      esac;
   done;
diff --git a/src/bash/funcs/setup-user b/src/bash/funcs/setup-user
--- a/src/bash/funcs/setup-user
+++ b/src/bash/funcs/setup-user
@@ -41,9 +41,9 @@ function setup-user() {
           ssh_keys="${2}";
           shift 2;
           ;;
-        --) shift; break;
+        --) shift 1; break;
           ;;
-        *) echo 'Invalid option: '"${1}"; exit 1;
+        *) echo 'Internal error.'; exit 1;
           ;;
      esac;
   done;
