Improve stack trace.

diff --git a/src/bash/funcs/maintenance-mode b/src/bash/funcs/maintenance-mode
--- a/src/bash/funcs/maintenance-mode
+++ b/src/bash/funcs/maintenance-mode
@@ -14,14 +14,22 @@ function disable-app-maintenance-mode() {
   return 0; # In case last test fails.
 };
 
-# Auto-warn user about maintenance mode on error.
-
-function auto-warn-about-app-maintenance-mode-on-error() {
-  echo 'WARNING: The app may still be in maintenance mode due to an error.'; stack-trace "$@";
-}; # e.g., `trap auto-warn-about-app-maintenance-mode-on-error ERR;`
-
 # Auto-disable maintenance mode on error.
+# e.g., `trap auto-disable-app-maintenance-mode-on-error ERR;`
 
 function auto-disable-app-maintenance-mode-on-error() {
-  disable-app-maintenance-mode; stack-trace "$@";
-}; # e.g., `trap auto-disable-app-maintenance-mode-on-error ERR;`
+  set +o xtrace; # Disable.
+  disable-app-maintenance-mode;
+  stack-trace "$@";
+};
+
+# Auto-warn user about maintenance mode on error.
+# e.g., `trap auto-warn-about-app-maintenance-mode-on-error ERR;`
+
+function auto-warn-about-app-maintenance-mode-on-error() {
+  set +o xtrace; # Disable; i.e., turn off comand printing.
+  echo '----------------------------------------------------------------------';
+  echo 'WARNING: The app may still be in maintenance mode due to an error.';
+  echo '----------------------------------------------------------------------';
+  stack-trace "$@";
+};
diff --git a/src/bash/strict-mode b/src/bash/strict-mode
--- a/src/bash/strict-mode
+++ b/src/bash/strict-mode
@@ -14,11 +14,12 @@ shopt -s globstar;
 shopt -s nullglob;
 shopt -s failglob;
 
-# Stack trace handler.
+# Stack trace on error.
 
 function stack-trace() {
+  set +o xtrace; # Disable.
+
   local last_command_status_code=$?;
-  set +o xtrace; # See: <http://jas.xyz/1my00XN>
   local exit_status_code="${1:-1}";
 
   echo '----------------------------------------------------------------------';
@@ -32,4 +33,5 @@ function stack-trace() {
     done;
   fi;
   echo 'Exiting w/ status `'"${exit_status_code}"'`.'; exit "${exit_status_code}";
-}; trap stack-trace ERR;
+};
+trap stack-trace ERR; # Trap errors & print a stack trace.
